//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadDHL.DataUploadWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataUploadWeb.InvoiceUploadSoap")]
    public interface InvoiceUploadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShipmentUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShipmentUpload(UploadDHL.DataUploadWeb.InvoiceShipmentHolder[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeighFileUpload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WeighFileUpload(string[] wdata, string batch);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoiceShipmentHolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private byte statusField;
        
        private string invoiceField;
        
        private System.DateTime invoiceDateField;
        
        private string vendorAccountField;
        
        private string aWBField;
        
        private int productField;
        
        private byte transportField;
        
        private System.Nullable<System.DateTime> shipdateField;
        
        private string customerNumberField;
        
        private string companyNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string country_IataField;
        
        private string reciever_CompanyNameField;
        
        private string reciever_Address1Field;
        
        private string reciever_Address2Field;
        
        private string reciever_CityField;
        
        private string reciever_StateField;
        
        private string reciever_ZipField;
        
        private string reciever_CountryField;
        
        private string reciever_Country_IataField;
        
        private string reciever_PhoneField;
        
        private string reciever_FaxField;
        
        private string reciever_EmailField;
        
        private string reciever_ReferenceField;
        
        private System.Nullable<byte> numberofColliesField;
        
        private string referenceField;
        
        private System.Nullable<decimal> total_WeightField;
        
        private System.Nullable<decimal> lengthField;
        
        private System.Nullable<decimal> widthField;
        
        private System.Nullable<decimal> heightField;
        
        private System.Nullable<decimal> vol_WeightField;
        
        private System.Nullable<decimal> billedWeightField;
        
        private System.Nullable<decimal> customevalueField;
        
        private System.Nullable<decimal> packValueField;
        
        private string packValutaField;
        
        private string descriptionField;
        
        private System.Nullable<decimal> costpriceField;
        
        private System.Nullable<decimal> salepriceField;
        
        private System.Nullable<decimal> oliField;
        
        private string serviceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VendorAccount {
            get {
                return this.vendorAccountField;
            }
            set {
                this.vendorAccountField = value;
                this.RaisePropertyChanged("VendorAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AWB {
            get {
                return this.aWBField;
            }
            set {
                this.aWBField = value;
                this.RaisePropertyChanged("AWB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("Product");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public byte Transport {
            get {
                return this.transportField;
            }
            set {
                this.transportField = value;
                this.RaisePropertyChanged("Transport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> Shipdate {
            get {
                return this.shipdateField;
            }
            set {
                this.shipdateField = value;
                this.RaisePropertyChanged("Shipdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Country_Iata {
            get {
                return this.country_IataField;
            }
            set {
                this.country_IataField = value;
                this.RaisePropertyChanged("Country_Iata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Reciever_CompanyName {
            get {
                return this.reciever_CompanyNameField;
            }
            set {
                this.reciever_CompanyNameField = value;
                this.RaisePropertyChanged("Reciever_CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Reciever_Address1 {
            get {
                return this.reciever_Address1Field;
            }
            set {
                this.reciever_Address1Field = value;
                this.RaisePropertyChanged("Reciever_Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Reciever_Address2 {
            get {
                return this.reciever_Address2Field;
            }
            set {
                this.reciever_Address2Field = value;
                this.RaisePropertyChanged("Reciever_Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Reciever_City {
            get {
                return this.reciever_CityField;
            }
            set {
                this.reciever_CityField = value;
                this.RaisePropertyChanged("Reciever_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Reciever_State {
            get {
                return this.reciever_StateField;
            }
            set {
                this.reciever_StateField = value;
                this.RaisePropertyChanged("Reciever_State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Reciever_Zip {
            get {
                return this.reciever_ZipField;
            }
            set {
                this.reciever_ZipField = value;
                this.RaisePropertyChanged("Reciever_Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Reciever_Country {
            get {
                return this.reciever_CountryField;
            }
            set {
                this.reciever_CountryField = value;
                this.RaisePropertyChanged("Reciever_Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Reciever_Country_Iata {
            get {
                return this.reciever_Country_IataField;
            }
            set {
                this.reciever_Country_IataField = value;
                this.RaisePropertyChanged("Reciever_Country_Iata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Reciever_Phone {
            get {
                return this.reciever_PhoneField;
            }
            set {
                this.reciever_PhoneField = value;
                this.RaisePropertyChanged("Reciever_Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Reciever_Fax {
            get {
                return this.reciever_FaxField;
            }
            set {
                this.reciever_FaxField = value;
                this.RaisePropertyChanged("Reciever_Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Reciever_Email {
            get {
                return this.reciever_EmailField;
            }
            set {
                this.reciever_EmailField = value;
                this.RaisePropertyChanged("Reciever_Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Reciever_Reference {
            get {
                return this.reciever_ReferenceField;
            }
            set {
                this.reciever_ReferenceField = value;
                this.RaisePropertyChanged("Reciever_Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<byte> NumberofCollies {
            get {
                return this.numberofColliesField;
            }
            set {
                this.numberofColliesField = value;
                this.RaisePropertyChanged("NumberofCollies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> Total_Weight {
            get {
                return this.total_WeightField;
            }
            set {
                this.total_WeightField = value;
                this.RaisePropertyChanged("Total_Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<decimal> Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<decimal> Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<decimal> Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> Vol_Weight {
            get {
                return this.vol_WeightField;
            }
            set {
                this.vol_WeightField = value;
                this.RaisePropertyChanged("Vol_Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<decimal> BilledWeight {
            get {
                return this.billedWeightField;
            }
            set {
                this.billedWeightField = value;
                this.RaisePropertyChanged("BilledWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<decimal> Customevalue {
            get {
                return this.customevalueField;
            }
            set {
                this.customevalueField = value;
                this.RaisePropertyChanged("Customevalue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<decimal> PackValue {
            get {
                return this.packValueField;
            }
            set {
                this.packValueField = value;
                this.RaisePropertyChanged("PackValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string PackValuta {
            get {
                return this.packValutaField;
            }
            set {
                this.packValutaField = value;
                this.RaisePropertyChanged("PackValuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<decimal> Costprice {
            get {
                return this.costpriceField;
            }
            set {
                this.costpriceField = value;
                this.RaisePropertyChanged("Costprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<decimal> Saleprice {
            get {
                return this.salepriceField;
            }
            set {
                this.salepriceField = value;
                this.RaisePropertyChanged("Saleprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<decimal> Oli {
            get {
                return this.oliField;
            }
            set {
                this.oliField = value;
                this.RaisePropertyChanged("Oli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string ServiceList {
            get {
                return this.serviceListField;
            }
            set {
                this.serviceListField = value;
                this.RaisePropertyChanged("ServiceList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvoiceUploadSoapChannel : UploadDHL.DataUploadWeb.InvoiceUploadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceUploadSoapClient : System.ServiceModel.ClientBase<UploadDHL.DataUploadWeb.InvoiceUploadSoap>, UploadDHL.DataUploadWeb.InvoiceUploadSoap {
        
        public InvoiceUploadSoapClient() {
        }
        
        public InvoiceUploadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceUploadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceUploadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceUploadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string ShipmentUpload(UploadDHL.DataUploadWeb.InvoiceShipmentHolder[] data) {
            return base.Channel.ShipmentUpload(data);
        }
        
        public string WeighFileUpload(string[] wdata, string batch) {
            return base.Channel.WeighFileUpload(wdata, batch);
        }
    }
}
