//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadDHL.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long ID { get; set; }
        public string Status { get; set; }
        public string Carrier { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceFileName { get; set; }
        public System.DateTime UploadDate { get; set; }
    }
}
