//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadDHL.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public long ID { get; set; }
        public long FK_Invoice { get; set; }
        public int Line { get; set; }
        public string Status { get; set; }
        public string Raw { get; set; }
        public string Fixed { get; set; }
        public string Factura { get; set; }
        public string TransKey { get; set; }
        public string GTXName { get; set; }

        public string Reason { get; set; }
        public Nullable<int> TransportProduct { get; set; }
        public Nullable<int> Product { get; set; }
        public string Awb { get; set; }
    }
}
