//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadDHL.DataConnections
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDKPalletrecord
    {
        public int Id { get; set; }
        public string Factura { get; set; }
        public string Sendingsnummer { get; set; }
        public System.DateTime Indleveringsdato { get; set; }
        public string Fragtbetaler { get; set; }
        public string Afsender { get; set; }
        public string Afsenderlandekode { get; set; }
        public string Afsenderpostnummer { get; set; }
        public string Afsenderstednavn { get; set; }
        public string Modtager { get; set; }
        public string ModtagerLandekode { get; set; }
        public string ModtagerPostnummer { get; set; }
        public string ModtagerStednavn { get; set; }
        public int Antalkolli { get; set; }
        public decimal FRBvægt { get; set; }
        public string Afsendersref { get; set; }
        public string Partiref { get; set; }
        public string Modtagersref { get; set; }
        public string Produkt { get; set; }
        public decimal Vægt { get; set; }
        public decimal Volum { get; set; }
        public decimal Ladmeter { get; set; }
        public string Fragtgrundlag { get; set; }
        public string Tillægsydelse { get; set; }
        public string Valuta { get; set; }
        public string Kurs { get; set; }
        public decimal Normalpris { get; set; }
        public decimal Tillægaftalepris { get; set; }
        public decimal Energitillægaftalepris { get; set; }
        public decimal Miljøtillægavtpris { get; set; }
        public decimal Kapacitetstillæg { get; set; }
        public decimal Hentetillægaftalepris { get; set; }
        public decimal Aftalepris { get; set; }
        public decimal TotalaftPris { get; set; }
        public string Afsenderidpåmodtager { get; set; }
        public string Sendingsindhold { get; set; }
        public string Godstype { get; set; }
        public string Fritekst { get; set; }
        public string Postnummer { get; set; }
    }
}
